name: Examples
on:
  push:
    branches:
      - main
    paths:
      - "examples/**"
  pull_request:
    branches:
      - main
    paths:
      - "examples/**"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - run: pnpm build:examples
      - run: pnpm playwright:install --with-deps # install browsers
      - run: pnpm test:examples

      # save test report
      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 30
