name: w3console
on:
  push:
    branches:
      - main
    paths:
      - "examples/react/w3console"
  pull_request:
    branches:
      - main
    paths:
      - "examples/react/w3console"
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - run: pnpm build
        working-directory: examples/react/w3console
      - uses: ./.github/actions/publish
        id: publish
        with:
          path_to_add: examples/react/w3console
          web3_token: ${{ secrets.WEB3_TOKEN }}
          dnslink_record: console
          dnslink_domain: web3.storage
          cf_pages_project: w3console
          cf_account_id: ${{ secrets.CF_ACCOUNT_ID }}
          cf_token: ${{ secrets.CF_TOKEN }}
      - name: Add Preview URLs as Job Summary
        run: echo "${{ steps.publish.outputs.summary }}" >> $GITHUB_STEP_SUMMARY
          